import { Fira_Code} from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar';
import { Provider } from '@/utils/Provider';

const firaCode = Fira_Code({ subsets: ["latin"] });
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    //Warning: Extra attributes from the server: class,style.  la solution est de mettre sur html suppressHydrationWarning pour eviter cette erreur
    <html lang="en"  suppressHydrationWarning >
      <body
        className={`${firaCode.className} h-full bg-amber-50 text-indigo-950 dark:bg-slate-950 dark:text-amber-50 dark:selection:bg-purple-500`}
      >
        <Provider>
          <Navbar/>
          <main className="h-full mx-auto max-w-5xl px-6">{children}</main>
        </Provider>
      </body>
    </html>
  )
}
