
import { Provider } from "@/utils/Provider";
import "./globals.css";
import CmsNavbar from "@/components/CmsNavbar";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}){
  return (
    <html lang="en">
      <body>
        <Provider>
          <CmsNavbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
